### ISSUE TITLE
[PE-D] Expiring list does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T16-3/tp#105] opened 2021-10-30 18:06 UTC
Expiring list does not work, still shows ingredient despite it not expiring within a week. From the image, 'fresh avocados' is listed as expiring even though it expires in a month.
![error3.PNG](https://raw.githubusercontent.com/YipWayne/ped/main/files/1a774d7b-db03-42c0-a2de-d27936329b6b.PNG)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YipWayne/ped#3

**Comment by JoshHDs** [comment] 2021-10-31 15:10
Duplicate of issue #91

**Closed** 2021-10-31 15:10 UTC
Labels: type.bug, priority.High
